### ISSUE TITLE
Running list of maintenance items

### ISSUE THREAD

**Issue by emcduffie** [USEPA/FrEDI#130]
Running list of minor items to check:

a. there are currently no damages (output as NA) for SLR sectors in the default run. Is this correct?
b. when running default fredi without custom inputs (all inputs = NULL), the physical impacts are not included in the output df (no column in df). Only reported if there is an agglevel  input. 
c. There is no physicalvariable measure listed for any of the Vibrio impacttypes. Mortality at least should be 'Premature Mortality'.
d. There are a number of sectors that only have economic damages, no physical impacts are calculated. For these sectors and impact types, the physical_impact column should report 'NA'. Instead, the economic impact results appear to be reported in both the physical and annual impact columns, which could cause user confusion.

**Comment by knoiva-indecon** [comment]
@emcduffie:

1. **a**. The issue with SLR sectors not appearing has been fixed.
2. **b**. When running default fredi without custom inputs (all inputs = NULL), the physical impacts are not included in the output df. This is because the default fredi runs with `aggLevels="all"` so "impacttype" is included in the aggregation levels. The physical impact columns (`physical_impacts` and `physicalmeasure`) are dropped since some sectors have different types of physical impacts, so aggregating on impact types has non-sensical results for some sectors.
3. **c** and **d**. We've added `physicalmeasure` values now for all impact types. Some sectors still have a value of `"N/A"` for impact types for which there is not a clear physical measure.
